apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nginx-ingress-role-nisa-binding-$(APP)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress-role-$(APP)
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-sa-$(APP)
