apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: broker
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: broker
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50