apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  name: broker
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 7032
  selector:
    app: broker
  type: LoadBalancer