apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces.yaml
- ../../../base

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- behavior: merge
  envs:
  - params
  name: configmap-parameters
- behavior: merge
  literals:
  - ENV=dev
  name: namespace-here-configmap-common
namespace: namespace-here
patchesStrategicMerge:
- service_patches.yaml