apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../nginx-ingress-dynamic-controller

configMapGenerator:
- name: configmap-nginx-controller-parameters
  behavior: merge
  envs:
  - nginx-controller-params
- name: tcp-services-stam-gateway
- name: udp-services-stam-gateway

generatorOptions:
  disableNameSuffixHash: true

